site_name: poetry-git-branch-plugin
site_url: https://dribia.github.io/poetry-git-branch-plugin/
site_description: A poetry plugin to store the current git branch into environment variable when poetry runs any command.
strict: true

repo_name: dribia/poetry-git-branch-plugin
repo_url: https://github.com/dribia/poetry-git-branch-plugin
edit_uri: ''

theme:
  name: material
  custom_dir: docs/theme
  language: en
  favicon: img/dribia-favicon-120x120.png
  logo: img/logo_dribia_d_blanc.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  features:
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - navigation.top
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    -
nav:
  - First steps: index.md
  - Example of usage: usage.md
  - Contribute: contribute.md
extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
    alias: true
    default: latest

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - toc:
      permalink: 📎
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
